### ISSUE TITLE
Users: Registration functionality

### ISSUE THREAD

**Issue by jen-huang** [matthewscode/puppey#4]
Users should be able to register through a form with the fields:
* email
* username
* password

URL:
`/join`

In DB - user table:
* id: primary key
* email: must be unique, not null
* username: must be unique, not null
* password: must be hashed and salted, not null
* points: integer, 0 by default
* creation_date: unix timestamp of user registration
* login_date: unix timestamp, null by default

In DB - authorities table:
* add row for general user role

Error handling:
* show message if email already registered
* show message if username already taken

**Comment by matthewscode** [comment]
Finished. We might have to talk about the authorities table.

**Comment by jen-huang** [comment]
Done in commit 9064a4e7cca19daffbadfcfe97df83fba8ac5bcb.

Let's start referencing issues in commit messages:
https://help.github.com/articles/closing-issues-via-commit-messages/
