### ISSUE TITLE
Users: Login and logout functionality

### ISSUE THREAD

**Issue by jen-huang** [matthewscode/puppey#5]
Users should be able to login through a form with the following fields:
* email
* password

URL:
`/login`

In DB:
* update login_date with unix timestamp on successful login

Error handling:
* show message if login unsuccessful

----

Users should be able to logout via URL:
`/logout`

**Comment by matthewscode** [comment]
completed.

**Comment by jen-huang** [comment]
@matthewscode Need to change form to use email for login instead of username.
